### ISSUE TITLE
【bug】100% 复现， 官方 web demo，1对1视频 挂断后再次拨打，会 hang 住，见详情图片

### ISSUE THREAD

**Issue by zhangdszq** [starrtc/starrtc-web-demo#9]
官方 web demo，1对1视频 挂断后再次拨打，会 hang 住，重启 server 后恢复

网络环境：局域网

浏览器：chrome 版本 75.0.3770.100（正式版本） （64 位）

web demo日志：
再次拨打后日志如下图：
![image](https://user-images.githubusercontent.com/5317416/71776183-10cc2380-2fc8-11ea-9ae3-ab16c4a83d9e.png)

server系统： ubuntu

**Comment by longqianxun** [comment]
已经在1.1.8版本解决
